FROM python:3.9-slim

WORKDIR /app

COPY ./requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY ./schemas.py /app/
COPY ./tasks.py /app/
COPY ./services.py /app/
COPY ./prompt.txt /app/

CMD ["celery", "-A", "tasks.celery_app", "worker", "--loglevel=info"]